SystemOrganization addCategory: #Balloon!
SystemOrganization addCategory: #Basic!
SystemOrganization addCategory: #Borders!
SystemOrganization addCategory: #Canvas!
SystemOrganization addCategory: #DockingBar!
SystemOrganization addCategory: #Events!
SystemOrganization addCategory: #Kernel!
SystemOrganization addCategory: #Layouts!
SystemOrganization addCategory: #List!
SystemOrganization addCategory: #Menus!
SystemOrganization addCategory: #MorphTreeWidget!
SystemOrganization addCategory: #'MorphTreeWidget-Announces'!
SystemOrganization addCategory: #'MorphTreeWidget-Pagination'!
SystemOrganization addCategory: #'Morphic-Base'!
SystemOrganization addCategory: #'Pluggable Widgets'!
SystemOrganization addCategory: #ProgressBar!
SystemOrganization addCategory: #'Text Support'!
SystemOrganization addCategory: #Widgets!
SystemOrganization addCategory: #'Widgets-Calendar'!
SystemOrganization addCategory: #WindowNotification!
SystemOrganization addCategory: #Windows!
