SystemOrganization addCategory: #'Morphic-Base'!
SystemOrganization addCategory: 'Morphic-Base-Balloon'!
SystemOrganization addCategory: 'Morphic-Base-Basic'!
SystemOrganization addCategory: 'Morphic-Base-Borders'!
SystemOrganization addCategory: 'Morphic-Base-Canvas'!
SystemOrganization addCategory: 'Morphic-Base-DockingBar'!
SystemOrganization addCategory: 'Morphic-Base-Events'!
SystemOrganization addCategory: 'Morphic-Base-Kernel'!
SystemOrganization addCategory: 'Morphic-Base-Layouts'!
SystemOrganization addCategory: 'Morphic-Base-List'!
SystemOrganization addCategory: 'Morphic-Base-Menus'!
SystemOrganization addCategory: 'Morphic-Base-MorphTreeWidget'!
SystemOrganization addCategory: 'Morphic-Base-MorphTreeWidget-Announces'!
SystemOrganization addCategory: 'Morphic-Base-MorphTreeWidget-Pagination'!
SystemOrganization addCategory: 'Morphic-Base-Pluggable Widgets'!
SystemOrganization addCategory: 'Morphic-Base-ProgressBar'!
SystemOrganization addCategory: 'Morphic-Base-Text Support'!
SystemOrganization addCategory: 'Morphic-Base-Widgets'!
SystemOrganization addCategory: 'Morphic-Base-Widgets-Calendar'!
SystemOrganization addCategory: 'Morphic-Base-WindowNotification'!
SystemOrganization addCategory: 'Morphic-Base-Windows'!
