SystemOrganization addCategory: #Nautilus!
SystemOrganization addCategory: 'Nautilus-Acceptors'!
SystemOrganization addCategory: 'Nautilus-Help'!
SystemOrganization addCategory: 'Nautilus-MCBindings'!
SystemOrganization addCategory: 'Nautilus-MorphTreeWidget-Extension'!
SystemOrganization addCategory: 'Nautilus-Tests'!
SystemOrganization addCategory: 'Nautilus-Tree'!
SystemOrganization addCategory: 'Nautilus-Widgets'!
