SystemOrganization addCategory: #Tools!
SystemOrganization addCategory: 'Tools-Base'!
SystemOrganization addCategory: 'Tools-Browser'!
SystemOrganization addCategory: 'Tools-Changes'!
SystemOrganization addCategory: 'Tools-ConfigurationBrowser'!
SystemOrganization addCategory: 'Tools-Debugger'!
SystemOrganization addCategory: 'Tools-Explorer'!
SystemOrganization addCategory: 'Tools-File Contents Browser'!
SystemOrganization addCategory: 'Tools-FileList'!
SystemOrganization addCategory: 'Tools-Finder'!
SystemOrganization addCategory: 'Tools-ImageCleaner'!
SystemOrganization addCategory: 'Tools-KeyChain'!
SystemOrganization addCategory: 'Tools-Process Browser'!
SystemOrganization addCategory: 'Tools-Profilers'!
SystemOrganization addCategory: 'Tools-Spotlight'!
SystemOrganization addCategory: 'Tools-SystemReporter'!
SystemOrganization addCategory: 'Tools-WebBrowser'!
